// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLDQaR4hNxEpzrfUEZTorJlPUPpGIeRr8',
    appId: '1:315398314807:web:a04840de29128f286dd8b2',
    messagingSenderId: '315398314807',
    projectId: 'iwatertestapp',
    authDomain: 'iwatertestapp.firebaseapp.com',
    databaseURL: 'https://iwatertestapp-default-rtdb.firebaseio.com',
    storageBucket: 'iwatertestapp.appspot.com',
    measurementId: 'G-ED5EELJM2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3GdKSPRfG91Vt8rrjrqcay6q6BMjXtto',
    appId: '1:315398314807:android:2838a72a9dc745806dd8b2',
    messagingSenderId: '315398314807',
    projectId: 'iwatertestapp',
    databaseURL: 'https://iwatertestapp-default-rtdb.firebaseio.com',
    storageBucket: 'iwatertestapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_zqGOWkbRxXfBdog6OhbcQdsnFHMxboc',
    appId: '1:315398314807:ios:ef6a1c3bd0d5a9e26dd8b2',
    messagingSenderId: '315398314807',
    projectId: 'iwatertestapp',
    databaseURL: 'https://iwatertestapp-default-rtdb.firebaseio.com',
    storageBucket: 'iwatertestapp.appspot.com',
    iosClientId: '315398314807-0kfuim9iuuou934atjmqdcav02v7dek2.apps.googleusercontent.com',
    iosBundleId: 'com.nimmalasujith.iwater',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_zqGOWkbRxXfBdog6OhbcQdsnFHMxboc',
    appId: '1:315398314807:ios:ef6a1c3bd0d5a9e26dd8b2',
    messagingSenderId: '315398314807',
    projectId: 'iwatertestapp',
    databaseURL: 'https://iwatertestapp-default-rtdb.firebaseio.com',
    storageBucket: 'iwatertestapp.appspot.com',
    iosClientId: '315398314807-0kfuim9iuuou934atjmqdcav02v7dek2.apps.googleusercontent.com',
    iosBundleId: 'com.nimmalasujith.iwater',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLDQaR4hNxEpzrfUEZTorJlPUPpGIeRr8',
    appId: '1:315398314807:web:348066d93bc1104f6dd8b2',
    messagingSenderId: '315398314807',
    projectId: 'iwatertestapp',
    authDomain: 'iwatertestapp.firebaseapp.com',
    databaseURL: 'https://iwatertestapp-default-rtdb.firebaseio.com',
    storageBucket: 'iwatertestapp.appspot.com',
    measurementId: 'G-CGJMC2HFXH',
  );
}
